Repository UnderTreeTech/waterdrop, pull requests merged in 2020-11, with the labels that each got.

#56 assign golangci-lint check folder
  .github/workflows/go.yml
  go.mod
  go.sum
  pkg/status/status.go
  tools/waterdrop/protoc/protobuf/pkg/gen/main.go
  tools/waterdrop/protoc/protobuf/pkg/generator/helper.go
  tools/waterdrop/protoc/protobuf/pkg/generator/http.go
  tools/waterdrop/protoc/protobuf/pkg/tag/ext_tags.go
Labels: Optimize

#57 Optimize/sql breaker
  pkg/database/mysql/sql.go
  pkg/status/status.go
Labels: Optimize

#60 sql conn query row does not finish trace span
  pkg/database/mysql/sql.go
Labels: Bug

#61 Optimize/default breaker
  examples/app/cmd/client/client.go
  examples/app/internal/server/grpc/server.go
  examples/app/internal/service/demo.go
  examples/rpc/client/client.go
  pkg/breaker/google_sre_breaker.go
  pkg/server/rpc/breaker.go
  pkg/server/rpc/client.go
  pkg/server/rpc/logger.go
  pkg/server/rpc/server.go
  pkg/server/rpc/validator.go
Labels: Optimize

#63 Enhancement/test coverage
  examples/app/cmd/client/client.go
  examples/app/cmd/server/server.go
  examples/app/internal/server/grpc/server.go
  examples/app/internal/server/http/server.go
  examples/http/server.go
  examples/rpc/client/client.go
  examples/rpc/server/server.go
  examples/websocket/server/server.go
  go.sum
  pkg/server/http/client/client.go
  pkg/server/http/config/config.go
  pkg/server/http/metadata/metadata.go
  pkg/server/http/middlewares/header.go
  pkg/server/http/middlewares/header_test.go
  pkg/server/http/middlewares/logger.go
  pkg/server/http/middlewares/logger_test.go
  pkg/server/http/middlewares/metric.go
  pkg/server/http/middlewares/metric_test.go
  pkg/server/http/middlewares/ratelimit/limiter.go
  pkg/server/http/middlewares/ratelimit/sentinel/sentinel.go
  pkg/server/http/middlewares/ratelimit/sentinel/sentinel_test.go
  pkg/server/http/middlewares/recovery.go
  pkg/server/http/middlewares/recovery_test.go
  pkg/server/http/middlewares/signature.go
  pkg/server/http/middlewares/signature_test.go
  pkg/server/http/middlewares/trace.go
  pkg/server/http/middlewares/trace_test.go
  pkg/server/http/server/server.go
  pkg/server/http/server/server_test.go
  pkg/server/http/websocket/websocket.go
  pkg/server/rpc/client/client.go
  pkg/server/rpc/client/client_test.go
  pkg/server/rpc/config/config.go
  pkg/server/rpc/interceptors/breaker_test.go
  pkg/server/rpc/interceptors/logger.go
  pkg/server/rpc/interceptors/logger_test.go
  pkg/server/rpc/interceptors/metric_test.go
  pkg/server/rpc/interceptors/recovery.go
  pkg/server/rpc/interceptors/recovery_test.go
  pkg/server/rpc/interceptors/sentinel_test.go
  pkg/server/rpc/interceptors/trace.go
  pkg/server/rpc/interceptors/trace_test.go
  pkg/server/rpc/interceptors/validator_test.go
  pkg/server/rpc/metadata/metadata.go
  pkg/server/rpc/recovery.go
  pkg/server/rpc/server/server.go
  pkg/server/rpc/server/server_test.go
  pkg/utils/xcollection/rolling_window_test.go
  pkg/utils/xstring/string.go
Labels: Enhancement

#64 add ip unit test
  docs/COPYRIGHT.txt
  pkg/breaker/googlesrebreaker.go
  pkg/log/log_test.go
  pkg/server/http/client/client.go
  pkg/utils/xcollection/lru.go
  pkg/utils/xcollection/lru_test.go
  pkg/utils/xcollection/priorityqueue.go
  pkg/utils/xcollection/priorityqueue_test.go
  pkg/utils/xcollection/rollingwindow.go
  pkg/utils/xcollection/rollingwindow_test.go
  pkg/utils/xnet/ip.go
  pkg/utils/xnet/ip_test.go
  pkg/utils/xsync/singlecall.go
  pkg/utils/xsync/singlecall_test.go
  pkg/utils/xsync/waitgroup.go
  pkg/utils/xsync/waitgroup_test.go
  pkg/utils/xtime/time.go
  pkg/utils/xtime/time_test.go
Labels: Enhancement
