Repository UnderTreeTech/waterdrop, pull requests merged in 2020-10, with the labels that each got.

#25 fix convert error to 500 status
  pkg/server/http/logger.go
Labels: Bug

#26 fix http middleware does not take effect
  examples/app/cmd/client.go
  examples/app/internal/server/http/server.go
Labels: Bug

#28 http middlewares
  examples/app/cmd/client.go
  examples/app/cmd/main.go
  examples/app/configs/application.toml
  examples/app/internal/server/http/server.go
  go.mod
  go.sum
  pkg/database/mysql/sql.go
  pkg/log/log.go
  pkg/server/http/client.go
  pkg/server/http/header.go
  pkg/server/http/logger.go
  pkg/server/http/metadata.go
  pkg/server/http/recovery.go
  pkg/server/http/signature.go
  pkg/status/status.go
  pkg/utils/xbuffer/README.md
  pkg/utils/xbuffer/bufferpool.go
  pkg/utils/xbuffer/bufferpool_test.go
  pkg/utils/xbuffer/sizedbufferpool.go
  pkg/utils/xbuffer/sizedbufferpool_test.go
  pkg/utils/xreply/reply.go
Labels: Enhancement

#33 fix read limit to max bytes when no explicit content-length
  pkg/server/http/signature.go
Labels: Bug, Enhancement

#36 Enhancement/tools
  .gitignore
  go.mod
  go.sum
  tools/waterdrop/main.go
  tools/waterdrop/protoc/action.go
  tools/waterdrop/protoc/cmd.go
  tools/waterdrop/protoc/common.go
  tools/waterdrop/protoc/grpc.go
  tools/waterdrop/protoc/protobuf/README.md
  tools/waterdrop/protoc/protobuf/pkg/extensions/gogoproto/gogo.pb.go
  tools/waterdrop/protoc/protobuf/pkg/extensions/gogoproto/gogo.pb.golden
  tools/waterdrop/protoc/protobuf/pkg/extensions/gogoproto/gogo.proto
  tools/waterdrop/protoc/protobuf/pkg/extensions/google/api/annotations.proto
  tools/waterdrop/protoc/protobuf/pkg/extensions/google/api/http.proto
  tools/waterdrop/protoc/protobuf/pkg/gen/main.go
  tools/waterdrop/protoc/protobuf/pkg/generator/command_line.go
  tools/waterdrop/protoc/protobuf/pkg/generator/generator.go
  tools/waterdrop/protoc/protobuf/pkg/generator/helper.go
  tools/waterdrop/protoc/protobuf/pkg/generator/http.go
  tools/waterdrop/protoc/protobuf/pkg/naming/go_naming.go
  tools/waterdrop/protoc/protobuf/pkg/naming/naming.go
  tools/waterdrop/protoc/protobuf/pkg/project/project.go
  tools/waterdrop/protoc/protobuf/pkg/tag/ext_tags.go
  tools/waterdrop/protoc/protobuf/pkg/tag/tags.go
  tools/waterdrop/protoc/protobuf/pkg/typemap/typemap.go
  tools/waterdrop/protoc/protobuf/pkg/utils/stringutils.go
  tools/waterdrop/protoc/protobuf/pkg/utils/utils.go
  tools/waterdrop/protoc/protobuf/protoc-gen-swagger/generator.go
  tools/waterdrop/protoc/protobuf/protoc-gen-swagger/main.go
  tools/waterdrop/protoc/protobuf/protoc-gen-swagger/types.go
  tools/waterdrop/protoc/swagger.go
  tools/waterdrop/swagger/cmd.go
  tools/waterdrop/testgen/common/parser.go
  tools/waterdrop/testgen/common/utils.go
  tools/waterdrop/testgen/utgen/cmd.go
  tools/waterdrop/testgen/utgen/gen.go
  tools/waterdrop/testgen/utgen/templete.go
  tools/waterdrop/utils/env.go
  tools/waterdrop/utils/helper.go
Labels: Enhancement

#42 Optimize/timeout
  pkg/server/http/metadata.go
  pkg/server/http/trace.go
  pkg/server/rpc/trace.go
Labels: Optimize

#52 Optimize/redis ping
  .github/workflows/go.yml
  pkg/database/redis/redis.go
Labels: Optimize

#54 add sentinel-go as rate limit component
  .github/workflows/go.yml
  examples/http/server.go
  go.mod
  go.sum
  pkg/ratelimit/setinel/sentinel.go
  pkg/ratelimit/setinel/sentinel_test.go
  pkg/server/http/ratelimit/limiter.go
  pkg/server/http/ratelimit/sentinel/sentinel.go
  pkg/server/http/ratelimit/sentinel/sentinel_test.go
  pkg/server/rpc/ratelimit/sentinel/sentinel.go
  pkg/server/rpc/ratelimit/sentinel/sentinel_test.go
Labels: Feature, Middleware

#55 Bump/version 0.2.0
  CHANGELOG.md
  pkg/version/version.go
Labels: Release
