Repository UnderTreeTech/waterdrop, pull requests merged in 2021-03, with the labels that each got.

#80 Compatible with multiple parameters of GOPATH
  tools/waterdrop/protoc/common.go
Labels: Bug

#82 support redis pipeline
  pkg/database/redis/redis.go
Labels: Enhancement, Feature

#83 [release] bump version to v1.1.0
  pkg/version/version.go
Labels: Release
